project './EntreGaudium.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'EntreGaudium' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EntreGaudium
  pod 'GoogleMaps', '6.0.1'

end
